In [332]:
import pandas as pd

In [397]:
csv = pd.read_csv("files\\library.csv", usecols= ["Identifier", "Publisher", "Title", "Author", "Date of Publication"])
csv.head(3)

,Identifier,Date of Publication,Publisher,Title,Author
0,206,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.
1,216,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A."
2,218,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A."

In [334]:
csv.loc[0]

Identifier                                           206
Date of Publication                                 1879
Publisher                               S. Tinsley & Co.
Title                  Walter Forbes. [A novel.] By A. A
Author                                             A. A.
Name: 0, dtype: object

In [335]:
csv["Identifier"].is_unique

True

In [336]:
csv.head(3)

,Identifier,Date of Publication,Publisher,Title,Author
0,206,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.
1,216,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A."
2,218,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A."

In [ ]:
csv.set_index("Identifier", inplace= True)

In [338]:
csv

,Date of Publication,Publisher,Title,Author
Identifier,,,,
206,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.
216,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A."
218,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A."
472,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S."
480,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S."
...,...,...,...,...
2466419,1817,NaN,A Gazetteer of the State of New Hampshire. Com...,"MERRILL, Eliphalet - and MERRILL (Phinehas)"
2466551,1881,Bentley & Son,East of the Jordan: a record of travel and obs...,"MERRILL, Selah."
2466552,1881],Congregational Publishing Society,Galilee in the time of Christ ... With an intr...,"MERRILL, Selah."
2466675,1897,"Smith, Elder & Co.",[The Grey Lady.],"MERRIMAN, Henry Seton - pseud. [i.e. Hugh Stow..."
2466691,1896,"Smith, Elder & Co.","The Money-Spinner, and other character notes. ...","MERRIMAN, Henry Seton - pseud. [i.e. Hugh Stow..."

In [339]:
csv.loc[206]

Date of Publication                                 1879
Publisher                               S. Tinsley & Co.
Title                  Walter Forbes. [A novel.] By A. A
Author                                             A. A.
Name: 206, dtype: object

In [340]:
# Pro DF:
csv.loc[206] # <- Hledá řádek pomocí indexu
csv.iloc[123] # <- Hledá řádek pomocí pořadí
csv["Author"] # <- Hledá sloupec

Identifier
206                                                    A. A.
216                                                A., A. A.
218                                                A., A. A.
472                                                A., E. S.
480                                                A., E. S.
                                 ...
2466419          MERRILL, Eliphalet - and MERRILL (Phinehas)
2466551                                      MERRILL, Selah.
2466552                                      MERRILL, Selah.
2466675    MERRIMAN, Henry Seton - pseud. [i.e. Hugh Stow...
2466691    MERRIMAN, Henry Seton - pseud. [i.e. Hugh Stow...
Name: Author, Length: 4999, dtype: object

In [341]:
csv.columns

Index(['Date of Publication', 'Publisher', 'Title', 'Author'], dtype='object')

In [342]:
csv.drop(columns= ["Author"], inplace= True)

In [343]:
csv

,Date of Publication,Publisher,Title
Identifier,,,
206,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A
216,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...
218,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...
472,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the..."
480,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it..."
...,...,...,...
2466419,1817,NaN,A Gazetteer of the State of New Hampshire. Com...
2466551,1881,Bentley & Son,East of the Jordan: a record of travel and obs...
2466552,1881],Congregational Publishing Society,Galilee in the time of Christ ... With an intr...
2466675,1897,"Smith, Elder & Co.",[The Grey Lady.]
2466691,1896,"Smith, Elder & Co.","The Money-Spinner, and other character notes. ..."

In [344]:
pd.DataFrame()
pd.Series()

Series([], dtype: object)

In [ ]:
df = pd.DataFrame([
    ["a", "b", "c"],
    ["A", "B", "C"]
],
columns= ["Sloupec1", "Sloupec2", "Sloupec3"], index= ["Hello", "World"])
df

      Sloupec1 Sloupec2 Sloupec3
Hello        a        b        c
World        A        B        C

In [346]:
df.loc["Hello"]

Sloupec1    a
Sloupec2    b
Sloupec3    c
Name: Hello, dtype: object

In [347]:
df.iloc[1]

Sloupec1    A
Sloupec2    B
Sloupec3    C
Name: World, dtype: object

In [348]:
type(df["Sloupec2"])

pandas.core.series.Series

In [349]:
ser = pd.Series(["A", "B", "C", 1], index= ["k+1", "k+2", "k+3", "k+4"])
ser

k+1    A
k+2    B
k+3    C
k+4    1
dtype: object

In [350]:
ser.iloc[0]

'A'

In [351]:
ser.loc["k+3"]

'C'

In [352]:
idx = pd.Series([True, False, True])
idx

0     True
1    False
2     True
dtype: bool

In [353]:
df2 = pd.DataFrame([
    [1, 2, 3, 4, 5],
    ["A", "B", "C", "D", "E"],
    ["a", "b", "c", "d", "e"]
])
df2

   0  1  2  3  4
0  1  2  3  4  5
1  A  B  C  D  E
2  a  b  c  d  e

In [354]:
df2[idx]

   0  1  2  3  4
0  1  2  3  4  5
2  a  b  c  d  e

In [355]:
df2[2] == 4

0    False
1    False
2    False
Name: 2, dtype: bool

In [356]:
df2[2]

0    3
1    C
2    c
Name: 2, dtype: object

In [370]:
idx = csv.head()["Date of Publication"].astype(int) > 1860
idx

Identifier
206     True
216     True
218     True
472    False
480    False
Name: Date of Publication, dtype: bool

In [378]:
ind = csv.head()["Date of Publication"].astype(int) > 1860
idx

Identifier
206     True
216     True
218     True
472    False
480    False
Name: Date of Publication, dtype: bool

In [380]:
csv.head()[idx]

,Date of Publication,Publisher,Title
Identifier,,,
206,1879,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A
216,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...
218,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...

In [386]:
results = pd.DataFrame([
    [1, 2, 2, 1],
    [3, 4, 2, 3],
    [2, 3, 3, 2]
], index=["St1", "St2", "St3"])
results

     0  1  2  3
St1  1  2  2  1
St2  3  4  2  3
St3  2  3  3  2

In [390]:
results.sum(axis= 1)

St1     6
St2    12
St3    10
dtype: int64

In [394]:
results.mean(axis= 1)

St1    1.5
St2    3.0
St3    2.5
dtype: float64

In [395]:
results.shape

(3, 4)

Docházka:
milan
michal s.
michael g.
david j.
patrik c.