In [46]:
import pandas as pd

In [47]:
data = {
    "Name": ["Alan", "Bob", "Clara", "Dave"],
    "Age": [21, 10, 68, 13],
    "English": [True, False, False, True],
    "Place": ["Dejvice", "Smíchov", "Holešovice", "Barandov"],
    "Score": [100, 200, 150, 50]
}

df = pd.DataFrame(data, index= ["A", "B", "C", "D"])

df # <- Pokud používáme JupiterNotebook, tak můžeme jen napsat co chceme vytisknout

    Name  Age  English       Place  Score
A   Alan   21     True     Dejvice    100
B    Bob   10    False     Smíchov    200
C  Clara   68    False  Holešovice    150
D   Dave   13     True    Barandov     50

In [ ]:
# Chceme získat pouze jména
# + jména a věk

df.loc[:, "Name"] # or df.loc[ :, ["Name", "Age"] ]

A     Alan
B      Bob
C    Clara
D     Dave
Name: Name, dtype: object

In [49]:
df["Name"]

A     Alan
B      Bob
C    Clara
D     Dave
Name: Name, dtype: object

In [50]:
# Chceme získat místo na řádku C
# + na řádku C a D

df.loc[["C", "D"], "Place"]

C    Holešovice
D      Barandov
Name: Place, dtype: object

In [51]:
# Pouze řádky 1 a 2 

df.iloc[[1, 2]]

    Name  Age  English       Place  Score
B    Bob   10    False     Smíchov    200
C  Clara   68    False  Holešovice    150

In [52]:
# Ukázat jenom řádky 1 a 2, ale za použití bool

df.loc[ [False, True, True, False] ]

    Name  Age  English       Place  Score
B    Bob   10    False     Smíchov    200
C  Clara   68    False  Holešovice    150

In [53]:
# Vytisknout řádky se jménem Bob
# + Bob a Klára

df["Name"] == "Bob"

A    False
B     True
C    False
D    False
Name: Name, dtype: bool

In [54]:
df.loc[  df["Name"] == "Bob"  ]

  Name  Age  English    Place  Score
B  Bob   10    False  Smíchov    200

In [55]:
df["Name"]

A     Alan
B      Bob
C    Clara
D     Dave
Name: Name, dtype: object

In [56]:
df["Name"].isin( ["Bob", "Clara"] )

A    False
B     True
C     True
D    False
Name: Name, dtype: bool

In [57]:
df.loc[  df["Name"].isin(["Bob", "Clara"])  ]

    Name  Age  English       Place  Score
B    Bob   10    False     Smíchov    200
C  Clara   68    False  Holešovice    150

In [58]:
# Vytvoř nový sloupec Old který bude True pokud Age > 60

df["Old"] = df["Age"] > 60

df

    Name  Age  English       Place  Score    Old
A   Alan   21     True     Dejvice    100  False
B    Bob   10    False     Smíchov    200  False
C  Clara   68    False  Holešovice    150   True
D   Dave   13     True    Barandov     50  False

In [59]:
# Přidej nový řádek s daty ["Eve", 18, True, "Řepy", 250, False]

len(df)

4

In [60]:
df.loc[len(df)] = ["Eve", 18, True, "Řepy", 250, False]
df

    Name  Age  English       Place  Score    Old
A   Alan   21     True     Dejvice    100  False
B    Bob   10    False     Smíchov    200  False
C  Clara   68    False  Holešovice    150   True
D   Dave   13     True    Barandov     50  False
4    Eve   18     True        Řepy    250  False

In [61]:
# Pomocí concat (Tohle je lepší)

new_row = pd.DataFrame({
    "Name": ["Frank"],
    "Age": [45],
    "English": [False],
    "Place": ["Břevnov"],
    "Score": [150],
    "Old": [False]
})

new_row

    Name  Age  English    Place  Score    Old
0  Frank   45    False  Břevnov    150  False

In [62]:
df = pd.concat([df, new_row])
df

    Name  Age  English       Place  Score    Old
A   Alan   21     True     Dejvice    100  False
B    Bob   10    False     Smíchov    200  False
C  Clara   68    False  Holešovice    150   True
D   Dave   13     True    Barandov     50  False
4    Eve   18     True        Řepy    250  False
0  Frank   45    False     Břevnov    150  False

In [63]:
# Vytvořte si DataFrame o alespoň 3 sloupcích
# + použijte na něj 3 různé filtry ( pomocí .loc .iloc nebo [] )